#!/usr/bin/env python3
"""CR-MDB-008 — generator: renders the 16 small-stack agent definitions, plus
the generated TOON codec copy that ships beside the tooling (CR-MDB-022 §S2).

Renders ``generator/templates/{red,green,verify,fix}.md.tmpl`` (string.Template)
with the per-stack parameters from ``generator/stacks/{arduino,bun,python,
quarkus}.toml`` into the repo-local package asset dir ``generator/agents/``
(CR-MDB-014 §S7 retarget), and renders ``scripts/toon.py`` from
``modelb_axi/toon.py`` — a real, self-contained module (never a re-export: a
deployed ``worktree-flow.py`` runs under a bare ``python3`` that cannot reach
the ``modelb_axi`` venv) carrying a do-not-hand-edit banner.

Verbs:
  build          render and write the target files in place
  --check        re-render to memory and diff against the asset files;
                 exit 0 when clean, exit 1 listing the drifted filenames
  --list         print the target file paths
  --stacks S,..  restrict to the given stacks (agent targets only)
  --roles R,..   restrict to the given roles (agent targets only)

Stdlib only. Deterministic output: stable target ordering, no timestamps.
The 13 bespoke defs (rust x4, vscode x4, electronics x4, inbox-analyst) are
NEVER targets. The codec copy is not stack- or role-scoped, so it is a target
of every invocation.
"""

from __future__ import annotations

import argparse
import sys
import tomllib
from pathlib import Path
from string import Template

GENERATOR_DIR = Path(__file__).resolve().parent
TEMPLATES_DIR = GENERATOR_DIR / "templates"
STACKS_DIR = GENERATOR_DIR / "stacks"
AGENTS_DIR = GENERATOR_DIR / "agents"

STACKS = ("arduino", "bun", "python", "quarkus")
ROLES = ("red", "green", "verify", "fix")

# The 16 small-stack agent files this generator owns — never the bespoke defs.
TARGETS = tuple(f"{stack}-{role}-agent.md" for stack in STACKS for role in ROLES)

REPO_ROOT = GENERATOR_DIR.parent

# The generated codec copy (CR-MDB-022 §S2): one hand-maintained source,
# one committed, drift-gated, self-contained artifact beside the tooling.
CODEC_SOURCE = REPO_ROOT / "modelb_axi" / "toon.py"
CODEC_TARGET = REPO_ROOT / "scripts" / "toon.py"

CODEC_BANNER = """\
# Owner: Model B (roundhouse/model-b) — adopted by CR-MDB-022 §S1.
# Consuming skills: none directly — imported by scripts/worktree-flow.py, which the
#   bootstrap, shutdown and model-b skills invoke.
#
# GENERATED by generator/build.py from modelb_axi/toon.py — do not hand-edit this
# file. Edit that source module and re-run `python3 generator/build.py build`; the
# `--check` drift gate fails on any hand-edit here. It is a real, self-contained
# module rather than a re-export, so a deployed worktree-flow.py invoked as a bare
# `python3` resolves it from beside itself with no modelb_axi on sys.path.
"""


def load_stack_params(stack: str) -> dict:
    """Parse one stack TOML via tomllib."""
    path = STACKS_DIR / f"{stack}.toml"
    with path.open("rb") as fh:
        return tomllib.load(fh)


def render(stack: str, role: str, params: dict) -> str:
    """Render one agent file's full content deterministically."""
    template = Template((TEMPLATES_DIR / f"{role}.md.tmpl").read_text(encoding="utf-8"))
    mapping = {
        "name": f"{stack}-{role}-agent",
        "description": params["description"][role],
        "frontmatter_extra": params["frontmatter"][role].strip("\n"),
        "display_name": params["display_name"],
        "test_command": params["test_command"],
        "register_command": params["register_command"],
        "unregister_command": params["unregister_command"],
        "crucible_reference": params["crucible_reference"],
        "stack_mechanics": params["mechanics"].strip("\n"),
        "role_gotchas": params["gotchas"][role].strip("\n"),
    }
    content = template.substitute(mapping)
    return content.rstrip("\n") + "\n"


def selected_targets(stacks: tuple[str, ...], roles: tuple[str, ...]):
    """Yield (stack, role, filename) in stable TARGETS order."""
    for stack in STACKS:
        if stack not in stacks:
            continue
        params = load_stack_params(stack)
        for role in ROLES:
            if role not in roles:
                continue
            yield stack, role, f"{stack}-{role}-agent.md", params


def render_codec() -> str:
    """The generated ``scripts/toon.py``: the banner plus its source verbatim."""
    return CODEC_BANNER + "\n" + CODEC_SOURCE.read_text(encoding="utf-8")


def cmd_build(stacks, roles) -> int:
    AGENTS_DIR.mkdir(parents=True, exist_ok=True)
    for _stack, role, name, params in selected_targets(stacks, roles):
        target = AGENTS_DIR / name
        target.write_text(render(_stack, role, params), encoding="utf-8")
        print(f"wrote {target}")
    CODEC_TARGET.write_text(render_codec(), encoding="utf-8")
    print(f"wrote {CODEC_TARGET}")
    return 0


def cmd_check(stacks, roles) -> int:
    drifted = []
    for stack, role, name, params in selected_targets(stacks, roles):
        live = AGENTS_DIR / name
        rendered = render(stack, role, params)
        if not live.is_file() or live.read_text(encoding="utf-8") != rendered:
            drifted.append(name)
    if (not CODEC_TARGET.is_file()
            or CODEC_TARGET.read_text(encoding="utf-8") != render_codec()):
        drifted.append(str(CODEC_TARGET.relative_to(REPO_ROOT)))
    if drifted:
        print("drifted (live differs from regeneration):")
        for name in drifted:
            print(name)
        return 1
    print("clean: live tree matches regeneration")
    return 0


def cmd_list(stacks, roles) -> int:
    for _stack, _role, name, _params in selected_targets(stacks, roles):
        print(AGENTS_DIR / name)
    print(CODEC_TARGET)
    return 0


def parse_filter(raw: str | None, allowed: tuple[str, ...], label: str) -> tuple[str, ...]:
    if raw is None:
        return allowed
    picked = tuple(item.strip() for item in raw.split(",") if item.strip())
    unknown = [item for item in picked if item not in allowed]
    if unknown:
        raise SystemExit(f"unknown {label}: {', '.join(unknown)} (allowed: {', '.join(allowed)})")
    return picked


def main(argv: list[str]) -> int:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument("command", nargs="?", choices=["build"],
                        help="build: render and write the live agent files")
    parser.add_argument("--check", action="store_true",
                        help="diff in-memory regeneration against the live files")
    parser.add_argument("--list", action="store_true", dest="list_targets",
                        help="print the target file paths")
    parser.add_argument("--stacks", help="comma-separated stack filter")
    parser.add_argument("--roles", help="comma-separated role filter")
    args = parser.parse_args(argv)

    actions = [bool(args.command), args.check, args.list_targets]
    if sum(actions) != 1:
        parser.error("exactly one of: build, --check, --list")

    stacks = parse_filter(args.stacks, STACKS, "stack")
    roles = parse_filter(args.roles, ROLES, "role")

    if args.check:
        return cmd_check(stacks, roles)
    if args.list_targets:
        return cmd_list(stacks, roles)
    return cmd_build(stacks, roles)


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
