"""RED-phase tests for CR-MDB-022 cycle C3 — §S5 (name the gate tool and
record its contract), §S6 (detach every reference from the local machine) and
§S7 (gates that keep the slot full).

Written before any §S5/§S6/§S7 production code lands on this branch. C1 GREEN
is `91ff12f` (eight scripts adopted into `scripts/`, installer asset class
`.agents/scripts`); C2 GREEN is `5b1bafb`/`fd01ed9` (`modelb_axi/toon.py` is
the one hand-maintained codec, `scripts/toon.py` is its GENERATED twin).

MEASURED PRE-STATE (2026-08-27, HEAD fd01ed9):

§S5 — the gate tool is UNNAMED.
  - `skills-src/model-b/references/orchestration-common.md:63` carries the
    whole serialize-heavy-gates protocol (the track's WAIT-FOR-FREE
    pre-flight, the gate-runner's ownership of the lock-file lifecycle, the
    coordinator as stale-lock arbiter) and says only "the gate-coordination
    tool" / "the GATE-RUNNER tool itself". `grep -rn gate-lock skills-src/
    AGENTS.md` returns ZERO lines, so a track following the published rule
    cannot find the binary. Both naming assertions fail.
  - `contracts/gate-lock.md` DOES NOT EXIST (`contracts/` holds
    `crucible-envelope.md`, `lean-ctx.md`, `mail-axi.md`, `sandesh-cli.md`
    and `.gitkeep`), so the two contract tests fail at their existence
    guard.
  - The two lock-path derivations ALREADY AGREE — see the standing-guard
    note below.

§S6 — twelve live `~/.claude/scripts/<one of the eight>` pairings remain,
not one:
    skills-src/memory-templates/java-orchestration.md:27   worktree-flow.py
    skills-src/memory-templates/rust-orchestration.md:11   worktree-flow.py
    skills-src/memory-templates/rust-orchestration.md:24   rust-crate-map.py
    skills-src/memory-templates/rust-orchestration.md:25   rust-dead-scan.py
    skills-src/memory-templates/rust-orchestration.md:26   rust-code-health.py
    scripts/skill-release-gate.py:30                       skill-release-gate.py
    docs/changes/CR-MDB-010-worktree-flow-axi.md:21,36     toon.py
    docs/changes/CR-MDB-022-tooling-adoption.md:82         toon.py
    docs/changes/README.md:89                              toon.py
    docs/changes/CR-MDB-023-code-health-skill-adoption.md:23,25
                                       rust-code-health.py, rust-dead-scan.py
  `scripts/skill-release-gate.py:30` is the only one under `scripts/`.
  SPEC DIVERGENCE, recorded not resolved: §S6's SCOPE prose (`:272-274`) lists
  six roots plus `AGENTS.md` and does NOT name `docs/changes/`, while §S6/AC1
  (`:383-385`) DOES. The AC text is authoritative, so this gate scans
  `docs/changes/` — which means GREEN must also reword four historical
  documents, two of them the acceptance criteria of an already-SHIPPED CR
  (`CR-MDB-010:21,36`) and one the spec of a not-yet-run CR
  (`CR-MDB-023:23,25`). That is a decision for the CR owner: either the AC's
  root list stands and the historical mentions are reworded to name the
  deployed store, or the AC is narrowed to the SCOPE's six roots. Do not
  quietly narrow this gate to make it pass.
  `archive/wave2/memory/{java,rust}-orchestration.md` hold 5 MORE pairings and
  are EXCLUDED — archived history is never rewritten to satisfy a gate, and
  the exclusion is asserted (not merely applied) so that stays true.
  None of the seven consuming surfaces names the deployed store path today:
  `grep -c '.agents/scripts'` is 0 in all seven.
  `tests/test_realhome_supersede.py` mentions NONE of the eight names
  (grep count 0 for each). CR-MDB-032 §S2 deleted that module, and with it
  the test of its skip guards; CR-MDB-020's anchoring gate covers the mirror.

§S7 — the slot is full but ungated. `scripts/` holds exactly the seven
  ADOPTED names plus the one GENERATED `toon.py`; `toon.py:5` carries the
  "GENERATED by generator/build.py from modelb_axi/toon.py" banner and none
  of the other seven does. No test enumerates the set, and no test asserts
  the built wheel's copy. `gate-lock.sh` and `skill-release-gate.py` have no
  consuming-skill reference under `skills-src/` (grep -rl count 0);
  `toon.py` has none DIRECTLY but is imported by `scripts/worktree-flow.py:146`,
  which three skills name — so consumption is resolved TRANSITIVELY here
  rather than pretending the codec is orphaned.

STANDING GUARDS — tests that PASS today, deliberately, and must keep passing:
  - `test_s5_both_projects_derive_a_byte_identical_lock_path` and
    `test_s5_lock_filename_literal_is_unchanged`. C1 adopted `gate-lock.sh`
    verbatim and Crucible's `rust-crucible.py` is the live
    gate-runner half, so the two derivations already agree
    (`<git-common-dir parent>/nai-gate.lock`, measured identical from BOTH
    the main tree and a linked worktree of the same fixture repo). These are
    the cross-project WIRE guards: a one-sided rename makes each tool wait
    on a path the other never writes, both conclude the gate is free, and two
    heavy regressions run concurrently — the exact environment-kill §S5's
    rule exists to prevent. §S5 RECORDS the contract; it does not touch the
    string.
  - `test_s6_relocated_tooling_resolves_its_siblings_from_beside_itself`.
    C1 adopted the bundle already self-contained (`worktree-flow.py:98`
    inserts its own directory on `sys.path`), so relocatability holds today.
    The guard stops §S6's repointing from reintroducing a home-anchored
    resolution.
  - `test_s7_scripts_dir_holds_the_seven_adopted_plus_the_generated_codec`,
    `test_s7_gate_rejects_an_unlisted_addition_and_a_missing_name`,
    `test_s7_gate_rejects_an_empty_asset_root` and
    `test_s7_built_wheel_carries_all_eight_tool_assets`. C1 filled the slot
    and `pyproject.toml:26` already force-includes `scripts` into
    `modelb_axi/_assets/scripts`, so the slot and the wheel are correct
    today; §S7's deliverable is the GATE, and a gate is only worth having if
    it discriminates, which the two mutation tests prove by breaking a
    throwaway copy of the asset root. The empty-root case is the state every
    wheel shipped between CR-MDB-014 and this CR.

Test boundary (PRD §D9): every sandbox is a `tempfile` directory removed in
`tearDown`; child processes that need a home get `HOME` pointed at one.
Nothing here reads, writes or deletes under the real `~/.claude` or
`~/.agents`, nothing invokes `chezmoi`, and the only real path this module
compares is a STRING built from `modelb_axi.deploy`'s own constant — never
stat'ed, never opened.

Crucible's installed `rust-crucible.py` (resolved through
`~/.crucible/crucible-clients.json`, CR-MDB-032 §S1; the test SKIPS naming
the manifest when it is absent) is a read-only REFERENCE plus an
OUT-OF-PROCESS oracle: its `_gate_lock_path` source segment is extracted by
`ast` and executed by a SEPARATE interpreter, so no module from their
installed clients is ever imported into this process and no file of theirs is
modified.

Stdlib only: ast, importlib.util, os, re, shutil, subprocess, sys, tempfile,
unittest, zipfile, pathlib.
"""

import ast
import importlib.util
import os
import re
import shutil
import subprocess
import sys
import tempfile
import unittest
import zipfile
from pathlib import Path

from modelb_axi import deploy
from tests._helpers import installed_crucible_file

REPO_ROOT = Path(__file__).resolve().parent.parent
SCRIPTS_DIR = REPO_ROOT / "scripts"
CONTRACTS_DIR = REPO_ROOT / "contracts"
GATE_LOCK_SH = SCRIPTS_DIR / "gate-lock.sh"
GATE_LOCK_CONTRACT = CONTRACTS_DIR / "gate-lock.md"
ORCH_COMMON = REPO_ROOT / "skills-src" / "model-b" / "references" / "orchestration-common.md"
DN_RATIONALIZATION = REPO_ROOT / "docs" / "research" / "DN-rationalization-plan-review.md"

#: §S7 — the asset class is SEVEN adopted scripts plus ONE generated artifact.
#: `toon.py` is not conflated with the adopted seven: C2 made it the output of
#: `generator/build.py` from `modelb_axi/toon.py`, gated by `--check`.
ADOPTED_SCRIPT_NAMES = (
    "worktree-flow.py",
    "schedule_db.py",
    "skill-release-gate.py",
    "rust-code-health.py",
    "rust-crate-map.py",
    "rust-dead-scan.py",
    "gate-lock.sh",
)
GENERATED_SCRIPT_NAMES = ("toon.py",)
TOOL_SCRIPT_NAMES = ADOPTED_SCRIPT_NAMES + GENERATED_SCRIPT_NAMES

#: §S2/AC3's banner contract (C2), reused here as the ADOPTED-vs-GENERATED
#: discriminator rather than a second convention.
GENERATED_BANNER_MARKERS = ("GENERATED", "modelb_axi/toon.py", "hand-edit")
BANNER_WINDOW = 20

#: §S5 — `scripts/gate-lock.sh`'s subcommand surface (its own header, :19-31,
#: and the `case "$CMD"` dispatch at :118-161).
GATE_LOCK_VERBS = (
    "acquire",
    "wait-acquire",
    "wait-free",
    "release",
    "status",
    "check",
    "force-release",
)

#: §S5 — the four exit codes and the keyword alternation each must be
#: documented with. Prose-tolerant: the code and a keyword must share a line
#: within 80 characters, in either order.
GATE_LOCK_EXIT_CODES = (
    (0, r"acquir\w+"),
    (1, r"held|holds|holder|another\s+track|locked"),
    (2, r"resourc\w+"),
    (5, r"time[d\s-]*out|timeout"),
)

#: §S5 — the shared mutex path. NOT a stray project name: Crucible's
#: `rust-crucible.py` writes and reclaims this exact file.
LOCK_FILENAME = "nai-gate.lock"
LOCK_FALLBACK_PATH = "/tmp/" + LOCK_FILENAME
RENAME_IS_A_CREQ = (
    f"{LOCK_FILENAME} is a CROSS-PROJECT WIRE CONTRACT, not a stray project "
    f"name to tidy up. Crucible's rust-crucible.py is the GATE-RUNNER "
    f"half of the same protocol: it derives the identical path "
    f"(_gate_lock_path), CREATES the file, DELETES it on finish/signal and "
    f"reclaims it when stale (STALE_LOCK_MAX_AGE_S), and names our script in "
    f"its own help text. A one-sided rename makes each tool wait on a path "
    f"the other never writes, so BOTH conclude the gate is free and two heavy "
    f"regressions run concurrently — the exact compile/resource starvation "
    f"env-KILL the serialize-heavy-gates rule exists to prevent. Renaming is a "
    f"CReq to Crucible (CR-MDB-022 §S5), never an edit in this repo."
)

#: §S5 — substance markers already carried by orchestration-common.md:63.
#: §S5/AC1 requires the WAIT-FOR-FREE rule to survive naming UNCHANGED in
#: substance, so naming must be additive.
WAIT_FOR_FREE_SUBSTANCE = (
    re.compile(r"WAIT-FOR-FREE", re.IGNORECASE),
    re.compile(r"does\s+NOT\s+create\s+the\s+lock", re.IGNORECASE),
    re.compile(r"OWNS\s+the\s+lock\s+FILE", re.IGNORECASE),
    re.compile(r"ESCALAT\w+", re.IGNORECASE),
    re.compile(r"STALE\s+lock", re.IGNORECASE),
)

#: §S5/AC2 — what `contracts/gate-lock.md` must state, as named requirements
#: so GREEN reads the shortfall off the failure rather than guessing.
CONTRACT_REQUIREMENTS = (
    (
        "lock path derivation (the parent of git's COMMON dir)",
        re.compile(r"git[\s-]*common[\s-]*dir|common\s+git\s+dir", re.IGNORECASE),
    ),
    ("lock filename", re.compile(re.escape(LOCK_FILENAME))),
    ("/tmp fallback path", re.compile(re.escape(LOCK_FALLBACK_PATH))),
    ("Model B's tool named", re.compile(r"gate-lock\.sh")),
    ("Crucible's gate-runner named", re.compile(r"rust-crucible\.py")),
    (
        "Model B WAITS and never creates the lock",
        re.compile(
            r"(?:wait\w*|observ\w+)[^\n]{0,200}?(?:never|does\s+not|not)\s+creat\w+"
            r"|(?:never|does\s+not|not)\s+creat\w+[^\n]{0,200}?(?:wait\w*|observ\w+)",
            re.IGNORECASE,
        ),
    ),
    (
        "Crucible CREATES the lock file",
        re.compile(r"creat\w+", re.IGNORECASE),
    ),
    (
        "Crucible DELETES the lock file",
        re.compile(r"delet\w+|remov\w+", re.IGNORECASE),
    ),
    (
        "Crucible RECLAIMS a stale lock",
        re.compile(r"reclaim\w*|stale", re.IGNORECASE),
    ),
)

#: §S5/AC4 — the rename prohibition the contract must record.
CONTRACT_RENAME_REQUIREMENTS = (
    (
        "renaming is forbidden",
        re.compile(
            r"(?:cannot|can\s+not|must\s+not|never|no)\s+[^\n]{0,120}?"
            r"(?:renam\w+|chang\w+)",
            re.IGNORECASE,
        ),
    ),
    (
        "a rename needs BOTH projects (not one side alone)",
        re.compile(
            r"one\s+side\s+alone|one-sided|unilateral\w*|both\s+(?:projects|sides)"
            r"|agreement\s+from\s+both",
            re.IGNORECASE,
        ),
    ),
)

#: §S6/AC1 — the INSTRUCTIONAL surfaces scanned for home-anchored tool paths:
#: the files that tell an agent what to run.
S6_SCAN_ROOTS = (
    "skills-src",
    "modelb_axi",
    "scripts",
    "contracts",
    "hooks-src",
    "AGENTS.md",
)

#: §S6/AC1 — EXCLUDED, and asserted excluded: the surfaces that must be FREE
#: to name the pattern in order to DESCRIBE or FORBID it. `docs/changes/` was
#: a scanned root at C3 RED, which made the gate unsatisfiable — a spec cannot
#: prohibit a string and also document its own prohibition (corrected
#: 2026-08-27; measured then: 12 pairings, 6 real instructional violations and
#: 6 prohibition-quotes in `docs/changes/`).
S6_EXCLUDED_ROOTS = (
    "docs/changes",
    "docs/research",
    "audits",
    "archive",
    "tests",
)

#: The frozen-history member of that set, guarded hardest: rewriting `archive/`
#: to satisfy a gate would destroy the record of what the CR detached from.
S6_EXCLUDED_ROOT = "archive"

#: The excluded roots that STILL hold home-anchored pairings (measured at C3
#: GREEN: docs/changes 6, archive 5, tests 2). The exclusion is load-bearing
#: precisely because those references SURVIVE; if they were rewritten, specs,
#: history or the gates themselves were edited to make this test green.
#: `docs/research/` and `audits/` hold none today — excluded on principle, so
#: describing the pattern there never becomes a violation later.
S6_EXCLUSION_IS_LOAD_BEARING = ("docs/changes", "archive", "tests")

#: The retired mirror location paired with one of the eight. Same shape as
#: the retired `tests/test_realhome_supersede.py`'s `LIVE_SCRIPTS_CRUCIBLE_REF_RE`:
#: prose that merely NAMES a tool without the retired path prefix is not a
#: home-anchored reference and is not flagged.
HOME_ANCHORED_TOOL_REF_RE = re.compile(
    r"\.claude/scripts/(?:" + "|".join(re.escape(n) for n in TOOL_SCRIPT_NAMES) + r")"
)

#: §S6/AC2 — the seven consuming surfaces that must name the deployed store.
S6_CONSUMING_SURFACES = (
    "skills-src/bootstrap/SKILL.md",
    "skills-src/shutdown/SKILL.md",
    "skills-src/model-b/references/orchestration-common.md",
    "skills-src/model-b/references/orchestration-track.md",
    "skills-src/memory-templates/java-orchestration.md",
    "skills-src/memory-templates/rust-orchestration.md",
    "AGENTS.md",
)

#: §S6/AC2 — DERIVED from `deploy.py`'s constant, never a hard-coded twin, so
#: the documented string and the deploy target cannot drift apart. Absent (a
#: pre-C1 tree) it stays None and the test fails on the missing constant
#: instead of on an AttributeError at import.
TOOL_SCRIPTS_STORE_RELDIR = getattr(deploy, "TOOL_SCRIPTS_STORE_RELDIR", None)
STORE_RELDIR_TOKEN = (
    TOOL_SCRIPTS_STORE_RELDIR.as_posix() if TOOL_SCRIPTS_STORE_RELDIR else None
)
#: The user-scope default: `modelb_axi/cli.py::resolve_target_root` documents
#: `Path.home()` as the default target root, so the path a track types is the
#: reldir under `~`.
DEPLOYED_STORE_PATH_TOKEN = f"~/{STORE_RELDIR_TOKEN}" if STORE_RELDIR_TOKEN else None

#: §S6/AC4 — the degrade marker `worktree-flow.py` prints when it cannot
#: resolve `schedule_db` from beside itself (C2 measured it at `:1060`/`:1130`).
SCHEDULE_DB_DEGRADE_MARKER = "schedule_db unavailable"

#: §S7/AC1 — scripts with NO consuming-skill reference in-tree, each with the
#: reason it is nevertheless RETAINED. A missing consumer is a LEAD, not a
#: fact: the design-lineage rule forbids reading absence as death. An entry
#: here is an explicit, reviewed decision — never a silent pass, never a
#: deletion. `gate-lock.sh` is deliberately ABSENT: §S5 gives it a consumer,
#: and this list must not become the place that excuses §S5 not happening.
NO_CONSUMER_ALLOW_LIST = {
    "skill-release-gate.py": (
        "RETAINED, not dead. Its only in-tree forward reference is "
        "docs/research/DN-rationalization-plan-review.md Wave 3 — 'wire "
        "build.py --check as drift gate (hook into skill-release-gate.py)' — "
        "so the wiring is PLANNED, not abandoned. Design lineage: it is most "
        "plausibly CR-MDB-012's release gate, which makes the missing "
        "consumer an unfinished thread to pull, not evidence of dead code. "
        "Do NOT delete it and do NOT let this entry stand in for the "
        "investigation."
    ),
}

#: The evidence each allow-list entry's reason must be checkable against, so
#: the list records a verified lead rather than a comforting sentence.
ALLOW_LIST_EVIDENCE = {
    "skill-release-gate.py": (
        (DN_RATIONALIZATION, re.compile(r"skill-release-gate\.py")),
        (None, re.compile(r"CR-MDB-012")),
    ),
}

WHEEL_ASSET_PREFIX = "modelb_axi/_assets/scripts/"

#: Executed by a SEPARATE interpreter: Crucible's `_gate_lock_path` source
#: segment is prepended to this, so nothing from their checkout is imported
#: here. argv[1] is the project directory to derive against.
_CRUCIBLE_DERIVATION_FN = "_gate_lock_path"
_CRUCIBLE_ORACLE_PREAMBLE = "import os\nimport subprocess\nimport sys\n"
_CRUCIBLE_ORACLE_TAIL = f"sys.stdout.write(str({_CRUCIBLE_DERIVATION_FN}(sys.argv[1])))\n"


def _crucible_rust_client():
    """``(path, "")`` for Crucible's installed gate-runner, or ``(None, reason)`` naming
    ``~/.crucible/crucible-clients.json`` (CR-MDB-032 §S1)."""
    return installed_crucible_file("rust")


GIT_FIXTURE_CONFIG = (
    "-c", "user.name=CR-MDB-022 fixture",
    "-c", "user.email=fixture@example.invalid",
    "-c", "commit.gpgsign=false",
    "-c", "init.defaultBranch=main",
)


def _read(path: Path) -> str:
    return path.read_text(encoding="utf-8", errors="replace")


def _rel(path: Path) -> str:
    try:
        return str(path.relative_to(REPO_ROOT))
    except ValueError:
        return str(path)


def _scan_files(root_rel: str) -> list:
    """Every readable file under a scan root (a file root scans itself)."""
    base = REPO_ROOT / root_rel
    if base.is_file():
        return [base]
    if not base.is_dir():
        return []
    return [
        p
        for p in sorted(base.rglob("*"))
        if p.is_file() and "__pycache__" not in p.parts
    ]


def _home_anchored_tool_refs(root_rel: str) -> list:
    """`(relative path, line number, matched text)` for every home-anchored
    reference to one of the eight under ``root_rel``."""
    found = []
    for path in _scan_files(root_rel):
        try:
            content = _read(path)
        except OSError:
            continue
        for line_no, line in enumerate(content.splitlines(), start=1):
            for match in HOME_ANCHORED_TOOL_REF_RE.finditer(line):
                found.append((_rel(path), line_no, match.group(0)))
    return found


def _names_exit_code(text: str, code: int, keyword_pattern: str) -> bool:
    """Does ``text`` document ``code`` beside a meaning keyword on one line?"""
    near = 80
    forward = re.compile(
        rf"\b{code}\b[^\n]{{0,{near}}}?(?:{keyword_pattern})", re.IGNORECASE
    )
    backward = re.compile(
        rf"(?:{keyword_pattern})[^\n]{{0,{near}}}?\b{code}\b", re.IGNORECASE
    )
    return bool(forward.search(text) or backward.search(text))


def _script_files(scripts_dir: Path) -> list:
    if not scripts_dir.is_dir():
        return []
    return sorted(
        p for p in scripts_dir.iterdir() if p.is_file() and p.name != ".gitkeep"
    )


def _carries_generated_banner(path: Path) -> bool:
    head = "\n".join(_read(path).splitlines()[:BANNER_WINDOW])
    return all(marker in head for marker in GENERATED_BANNER_MARKERS)


def _asset_slot_violations(scripts_dir: Path) -> list:
    """The §S7 asset-slot gate, PARAMETERIZED by asset root so it can be run
    against a mutated throwaway copy as well as the live tree.

    Returns one violation string per fault, each naming the offending name:
    an empty/absent root, a missing expected name, an unlisted addition.
    """
    violations = []
    if not scripts_dir.is_dir():
        return [f"asset root {scripts_dir} does not exist"]
    present = {p.name for p in _script_files(scripts_dir)}
    if not present:
        return [f"asset root {scripts_dir} is EMPTY — the wheel would ship no tooling"]
    expected = set(TOOL_SCRIPT_NAMES)
    for name in sorted(expected - present):
        violations.append(f"missing expected tool script: {name}")
    for name in sorted(present - expected):
        violations.append(f"unlisted addition under the asset root: {name}")
    return violations


def _skill_referenced_names() -> set:
    """Tool names a skill source under ``skills-src/`` names directly."""
    referenced = set()
    for path in _scan_files("skills-src"):
        try:
            content = _read(path)
        except OSError:
            continue
        for name in TOOL_SCRIPT_NAMES:
            if name in content:
                referenced.add(name)
    return referenced


def _sibling_import_edges() -> dict:
    """`{importer name: {imported sibling name}}` over ``scripts/*.py``.

    Consumption can be TRANSITIVE: `scripts/toon.py` is named by no skill but
    is imported by `scripts/worktree-flow.py`, which three skills name.
    """
    by_module = {p.stem: p.name for p in _script_files(SCRIPTS_DIR) if p.suffix == ".py"}
    edges = {}
    for path in _script_files(SCRIPTS_DIR):
        if path.suffix != ".py":
            continue
        try:
            tree = ast.parse(_read(path))
        except SyntaxError:
            continue
        imported = set()
        for node in ast.walk(tree):
            if isinstance(node, ast.Import):
                candidates = [alias.name.split(".")[0] for alias in node.names]
            elif isinstance(node, ast.ImportFrom):
                candidates = [(node.module or "").split(".")[0]]
            else:
                continue
            for module in candidates:
                sibling = by_module.get(module)
                if sibling and sibling != path.name:
                    imported.add(sibling)
        edges[path.name] = imported
    return edges


def _consumed_names() -> set:
    """Names resolved either DIRECTLY by a skill or TRANSITIVELY through a
    sibling script that is itself directly referenced."""
    direct = _skill_referenced_names()
    resolved = set(direct)
    edges = _sibling_import_edges()
    for importer, imported in edges.items():
        if importer in direct:
            resolved |= imported
    return resolved


def _run(argv, **kwargs) -> subprocess.CompletedProcess:
    return subprocess.run(argv, capture_output=True, text=True, timeout=300, **kwargs)


def _init_git_fixture(root: Path) -> Path:
    """A throwaway git repo with one commit and one LINKED WORKTREE, so the
    `--git-common-dir` branch both derivations rely on is really exercised.
    Entirely inside ``root``; no worktree of this repo is ever created."""
    main = root / "main-tree"
    main.mkdir(parents=True)
    _run(["git", *GIT_FIXTURE_CONFIG, "init", "-q", str(main)])
    _run(["git", *GIT_FIXTURE_CONFIG, "-C", str(main), "commit", "-q",
          "--allow-empty", "-m", "fixture"])
    _run(["git", *GIT_FIXTURE_CONFIG, "-C", str(main), "worktree", "add", "-q",
          str(root / "linked-wt"), "-b", "side"])
    return main


def _gate_lock_derived_path(check_dir: Path) -> str:
    """`gate-lock.sh`'s OWN derivation, read off its `status` output (`:119`
    prints `lock: $LOCK` first), driven as a subprocess."""
    env = dict(os.environ)
    env["GATE_CHECK_DIR"] = str(check_dir)
    result = _run(["bash", str(GATE_LOCK_SH), "status"], env=env, cwd=str(check_dir))
    for line in result.stdout.splitlines():
        if line.startswith("lock:"):
            return line.split(":", 1)[1].strip()
    raise AssertionError(
        f"gate-lock.sh status printed no `lock:` line (rc={result.returncode}): "
        f"{result.stdout!r} {result.stderr!r}"
    )


def _crucible_derivation_source(client: Path) -> str:
    """AST-extract Crucible's `_gate_lock_path` source segment from the
    installed ``client``. Never imported — the segment is handed to a
    separate interpreter."""
    text = _read(client)
    tree = ast.parse(text)
    for node in tree.body:
        if isinstance(node, ast.FunctionDef) and node.name == _CRUCIBLE_DERIVATION_FN:
            segment = ast.get_source_segment(text, node)
            if segment:
                return segment
    raise AssertionError(
        f"{_CRUCIBLE_DERIVATION_FN} not found in {client} — the "
        f"gate-runner half of the protocol moved; re-measure before trusting "
        f"either derivation."
    )


def _crucible_derived_path(client: Path, project_dir: Path) -> str:
    program = (
        _CRUCIBLE_ORACLE_PREAMBLE + _crucible_derivation_source(client) + "\n" + _CRUCIBLE_ORACLE_TAIL
    )
    result = _run([sys.executable, "-c", program, str(project_dir)])
    if result.returncode != 0:
        raise AssertionError(
            f"Crucible's derivation failed out of process: {result.stderr.strip()[:400]}"
        )
    return result.stdout.strip()


class GateLockContractS5Test(unittest.TestCase):
    """§S5 — the gate tool is named and its cross-project contract recorded."""

    def _require_contract(self) -> str:
        if not GATE_LOCK_CONTRACT.is_file():
            self.fail(
                f"§S5/AC2: {_rel(GATE_LOCK_CONTRACT)} does not exist. The "
                f"serialize-heavy-gates protocol is shared with Crucible's "
                f"rust-crucible.py and is recorded nowhere in this "
                f"repo, so neither side can check the other's half."
            )
        return _read(GATE_LOCK_CONTRACT)

    def test_s5_orchestration_common_names_the_gate_tool_verbs_and_exit_codes(self):
        self.assertTrue(
            ORCH_COMMON.is_file(), f"{_rel(ORCH_COMMON)} is missing"
        )
        text = _read(ORCH_COMMON)

        self.assertIn(
            GATE_LOCK_SH.name, text,
            f"§S5/AC1: {_rel(ORCH_COMMON)} specifies the whole "
            f"serialize-heavy-gates protocol and never names the tool that "
            f"implements it (it says only 'the gate-coordination tool'), so a "
            f"track following the published rule cannot find the binary. It "
            f"is scripts/{GATE_LOCK_SH.name}.",
        )

        missing_verbs = [v for v in GATE_LOCK_VERBS if not re.search(
            rf"(?<![\w-]){re.escape(v)}(?![\w-])", text)]
        self.assertEqual(
            [], missing_verbs,
            f"§S5/AC1: {_rel(ORCH_COMMON)} must list all seven "
            f"{GATE_LOCK_SH.name} verbs {list(GATE_LOCK_VERBS)}; missing "
            f"{missing_verbs}.",
        )

        missing_codes = [
            code for code, keywords in GATE_LOCK_EXIT_CODES
            if not _names_exit_code(text, code, keywords)
        ]
        self.assertEqual(
            [], missing_codes,
            f"§S5/AC1: {_rel(ORCH_COMMON)} must document the four exit codes "
            f"(0 acquired, 1 held by another track, 2 resources loaded, "
            f"5 timeout) beside their meanings; undocumented: {missing_codes}.",
        )

        unchanged = [p.pattern for p in WAIT_FOR_FREE_SUBSTANCE if not p.search(text)]
        self.assertEqual(
            [], unchanged,
            f"§S5/AC1: naming the tool must be ADDITIVE — the WAIT-FOR-FREE "
            f"rule already carried must be unchanged in substance. These "
            f"substance markers were present pre-C3 and are now gone: "
            f"{unchanged}.",
        )

    def test_s5_contract_records_path_verbs_exit_codes_and_ownership(self):
        text = self._require_contract()
        missing = [
            label for label, pattern in CONTRACT_REQUIREMENTS
            if not pattern.search(text)
        ]
        self.assertEqual(
            [], missing,
            f"§S5/AC2: {_rel(GATE_LOCK_CONTRACT)} must state the lock path "
            f"derivation, the verb set, the exit codes and the ownership "
            f"division — Model B's gate-lock.sh WAITS and never creates the "
            f"lock; Crucible's rust-crucible.py creates, deletes and reclaims "
            f"it. Unstated: {missing}.",
        )

        missing_verbs = [v for v in GATE_LOCK_VERBS if not re.search(
            rf"(?<![\w-]){re.escape(v)}(?![\w-])", text)]
        self.assertEqual(
            [], missing_verbs,
            f"§S5/AC2: {_rel(GATE_LOCK_CONTRACT)} must record all seven verbs; "
            f"missing {missing_verbs}.",
        )

        missing_codes = [
            code for code, keywords in GATE_LOCK_EXIT_CODES
            if not _names_exit_code(text, code, keywords)
        ]
        self.assertEqual(
            [], missing_codes,
            f"§S5/AC2: {_rel(GATE_LOCK_CONTRACT)} must record all four exit "
            f"codes with their meanings; undocumented: {missing_codes}.",
        )

    def test_s5_contract_records_that_the_lock_filename_binds_both_projects(self):
        text = self._require_contract()
        missing = [
            label for label, pattern in CONTRACT_RENAME_REQUIREMENTS
            if not pattern.search(text)
        ]
        self.assertEqual(
            [], missing,
            f"§S5/AC4: {_rel(GATE_LOCK_CONTRACT)} must state that the lock "
            f"FILENAME cannot change on one side alone. Unstated: {missing}. "
            f"{RENAME_IS_A_CREQ}",
        )

    def test_s5_both_projects_derive_a_byte_identical_lock_path(self):
        """STANDING GUARD (passes today). Compares the two DERIVATIONS against
        one fixture git layout: `gate-lock.sh` driven as a subprocess, and
        Crucible's `_gate_lock_path` extracted and evaluated out of process.
        Neither side is read and trusted."""
        self.assertTrue(GATE_LOCK_SH.is_file(), f"{_rel(GATE_LOCK_SH)} is missing")
        client, reason = _crucible_rust_client()
        if client is None:
            self.skipTest(
                f"Crucible's gate-runner is not installed ({reason}), so the "
                f"other half of the derivation cannot be evaluated; the contract "
                f"in {_rel(GATE_LOCK_CONTRACT)} is then the only record."
            )
        sandbox = Path(tempfile.mkdtemp(prefix="mdb022-c3-lockpath-"))
        try:
            main_tree = _init_git_fixture(sandbox)
            linked_wt = sandbox / "linked-wt"
            expected = str(main_tree / LOCK_FILENAME)
            for label, probe_dir in (("main tree", main_tree), ("linked worktree", linked_wt)):
                if not probe_dir.is_dir():
                    self.skipTest(f"git could not create the {label} fixture")
                ours = _gate_lock_derived_path(probe_dir)
                theirs = _crucible_derived_path(client, probe_dir)
                self.assertEqual(
                    ours, theirs,
                    f"§S5/AC3: from the {label}, scripts/gate-lock.sh derives "
                    f"{ours!r} while Crucible's rust-crucible.py derives "
                    f"{theirs!r}. The two halves of the gate protocol are "
                    f"waiting on DIFFERENT files: both will conclude the gate "
                    f"is free and two heavy regressions will run concurrently. "
                    f"{RENAME_IS_A_CREQ}",
                )
                self.assertEqual(
                    expected, ours,
                    f"§S5/AC3: from the {label} the shared lock must resolve to "
                    f"the MAIN repo root ({expected!r}) so the mutex spans every "
                    f"worktree; got {ours!r}.",
                )
        finally:
            shutil.rmtree(sandbox, ignore_errors=True)

    def test_s5_lock_filename_literal_is_unchanged(self):
        """STANDING GUARD (passes today) against a well-intentioned rename."""
        self.assertTrue(GATE_LOCK_SH.is_file(), f"{_rel(GATE_LOCK_SH)} is missing")
        text = _read(GATE_LOCK_SH)
        self.assertIn(
            LOCK_FILENAME, text,
            f"§S5/AC4: the literal {LOCK_FILENAME!r} has left "
            f"{_rel(GATE_LOCK_SH)}. {RENAME_IS_A_CREQ}",
        )
        self.assertIn(
            LOCK_FALLBACK_PATH, text,
            f"§S5/AC4: the non-git fallback {LOCK_FALLBACK_PATH!r} has left "
            f"{_rel(GATE_LOCK_SH)}; Crucible's derivation has no fallback of "
            f"its own, so this branch is part of the shared contract. "
            f"{RENAME_IS_A_CREQ}",
        )


class DetachmentS6Test(unittest.TestCase):
    """§S6 — no Model B surface names the local machine's retired mirror."""

    def test_s6_zero_home_anchored_references_to_the_eight_on_live_surfaces(self):
        offending = []
        for root in S6_SCAN_ROOTS:
            offending.extend(_home_anchored_tool_refs(root))
        self.assertEqual(
            [], offending,
            f"§S6/AC1: zero occurrences of `.claude/scripts/` paired with any "
            f"of the eight tool names are permitted under {list(S6_SCAN_ROOTS)}. "
            f"The deployed store ({DEPLOYED_STORE_PATH_TOKEN}) is the only "
            f"path a Model B surface names; `~/.claude/scripts/` is "
            f"chezmoi-managed and reverted on the next apply. Found "
            f"{len(offending)}: {offending}",
        )

    def test_s6_excluded_surfaces_are_excluded_from_the_detachment_gate(self):
        overlap = [root for root in S6_EXCLUDED_ROOTS if root in S6_SCAN_ROOTS]
        self.assertEqual(
            [], overlap,
            f"§S6/AC1: {overlap} is both scanned and excluded. The excluded "
            f"set {list(S6_EXCLUDED_ROOTS)} must stay FREE to name the "
            f"pattern in order to describe or forbid it — a CR spec cannot "
            f"prohibit a string and also document its own prohibition, and "
            f"neither can this module's own gates.",
        )
        self.assertNotIn(
            S6_EXCLUDED_ROOT, S6_SCAN_ROOTS,
            f"§S6/AC1: {S6_EXCLUDED_ROOT}/ must never be scanned — it is "
            f"frozen history and rewriting it to satisfy this gate would "
            f"destroy the record of what the CR detached from.",
        )
        archive_root = REPO_ROOT / S6_EXCLUDED_ROOT
        self.assertTrue(
            archive_root.is_dir(),
            f"§S6/AC1: {S6_EXCLUDED_ROOT}/ is gone, so this exclusion no "
            f"longer means anything — re-measure the gate's scope.",
        )
        archived = _home_anchored_tool_refs(S6_EXCLUDED_ROOT)
        self.assertNotEqual(
            [], archived,
            f"§S6/AC1: {S6_EXCLUDED_ROOT}/ held home-anchored references to "
            f"the eight (5 in archive/wave2/memory/ at C3 RED) and now holds "
            f"none. The exclusion is load-bearing precisely because those "
            f"references survive; if they were rewritten, archived history was "
            f"edited to make a gate green.",
        )
        emptied = [
            root for root in S6_EXCLUSION_IS_LOAD_BEARING
            if not _home_anchored_tool_refs(root)
        ]
        self.assertEqual(
            [], emptied,
            f"§S6/AC1: {emptied} were excluded because they still NAME the "
            f"pattern in order to describe or forbid it, and now name it "
            f"nowhere. Either the exclusion is pointless or a spec, a frozen "
            f"record, or a test was rewritten to make a gate green — "
            f"re-measure before trusting this module.",
        )

    def test_s6_seven_consuming_surfaces_name_the_deployed_store_path(self):
        self.assertIsNotNone(
            TOOL_SCRIPTS_STORE_RELDIR,
            "§S6/AC2: modelb_axi/deploy.py carries no "
            "TOOL_SCRIPTS_STORE_RELDIR, so the deployed path cannot be "
            "derived and any documented string would be a hard-coded twin.",
        )
        # PRD §D9: string/path algebra only — the deploy target is never
        # stat'ed, opened or written by this module.
        self.assertEqual(
            str(Path.home() / TOOL_SCRIPTS_STORE_RELDIR),
            os.path.expanduser(DEPLOYED_STORE_PATH_TOKEN),
            f"§S6/AC2: the documented spelling "
            f"{DEPLOYED_STORE_PATH_TOKEN!r} and deploy.py's user-scope target "
            f"({Path.home() / TOOL_SCRIPTS_STORE_RELDIR}) are two different "
            f"paths — the documentation and the installer have drifted.",
        )

        missing = []
        for rel in S6_CONSUMING_SURFACES:
            path = REPO_ROOT / rel
            if not path.is_file():
                missing.append(f"{rel} (file missing)")
                continue
            if DEPLOYED_STORE_PATH_TOKEN not in _read(path):
                missing.append(rel)
        self.assertEqual(
            [], missing,
            f"§S6/AC2: every consuming surface must name the deployed store "
            f"path {DEPLOYED_STORE_PATH_TOKEN!r} — derived from "
            f"deploy.py::TOOL_SCRIPTS_STORE_RELDIR, not duplicated — so the "
            f"documented string and the deploy target cannot drift apart. "
            f"Surfaces not naming it: {missing}",
        )

    def test_s6_relocated_tooling_resolves_its_siblings_from_beside_itself(self):
        """STANDING GUARD (passes today): the bundle was adopted already
        self-contained. Stops §S6's repointing from reintroducing a
        home-anchored resolution."""
        for name in TOOL_SCRIPT_NAMES:
            self.assertTrue(
                (SCRIPTS_DIR / name).is_file(),
                f"§S6/AC4: scripts/{name} is missing, so the bundle cannot be "
                f"relocated as a unit.",
            )
        sandbox = Path(tempfile.mkdtemp(prefix="mdb022-c3-relocate-"))
        try:
            tools = sandbox / "arbitrary" / "elsewhere"
            tools.mkdir(parents=True)
            for name in TOOL_SCRIPT_NAMES:
                shutil.copy2(SCRIPTS_DIR / name, tools / name)
            fake_home = sandbox / "home"
            (fake_home / ".claude").mkdir(parents=True)
            neutral_cwd = sandbox / "neutral"
            neutral_cwd.mkdir()
            fixture = _init_git_fixture(sandbox / "fixture")

            env = {
                k: v for k, v in os.environ.items()
                if k not in ("PYTHONPATH", "PYTHONHOME")
            }
            env["HOME"] = str(fake_home)

            help_run = _run(
                [sys.executable, str(tools / "worktree-flow.py"), "--help"],
                env=env, cwd=str(neutral_cwd),
            )
            self.assertEqual(
                0, help_run.returncode,
                f"§S6/AC4: `worktree-flow.py --help` must exit 0 from an "
                f"arbitrary directory outside the repo; rc="
                f"{help_run.returncode}, stderr={help_run.stderr.strip()[:400]}",
            )

            status_run = _run(
                [sys.executable, str(tools / "worktree-flow.py"),
                 "status", "--project-dir", str(fixture)],
                env=env, cwd=str(neutral_cwd),
            )
            self.assertEqual(
                0, status_run.returncode,
                f"§S6/AC4: the relocated `status` must exit 0; rc="
                f"{status_run.returncode}, stderr="
                f"{status_run.stderr.strip()[:400]}",
            )
            self.assertTrue(
                status_run.stdout.lstrip().startswith("axi:"),
                f"§S6/AC4: the relocated `status` emitted no TOON envelope, so "
                f"`toon` was not resolved from beside the script: "
                f"{status_run.stdout[:200]!r}",
            )
            self.assertNotIn(
                SCHEDULE_DB_DEGRADE_MARKER, status_run.stdout + status_run.stderr,
                f"§S6/AC4: the relocated `status` degraded with "
                f"{SCHEDULE_DB_DEGRADE_MARKER!r}, so `schedule_db` was not "
                f"resolved from beside the script.",
            )

            probe = (
                "import sys\n"
                "sys.path.insert(0, sys.argv[1])\n"
                "import schedule_db, toon\n"
                "print(schedule_db.__file__)\n"
                "print(toon.__file__)\n"
                "print('\\n'.join(p for p in sys.path if p))\n"
            )
            probe_run = _run(
                [sys.executable, "-c", probe, str(tools)],
                env=env, cwd=str(neutral_cwd),
            )
            self.assertEqual(
                0, probe_run.returncode,
                f"§S6/AC4: importing `toon`/`schedule_db` from the relocated "
                f"directory failed: {probe_run.stderr.strip()[:400]}",
            )
            lines = probe_run.stdout.splitlines()
            resolved, path_entries = lines[:2], lines[2:]
            for resolved_file in resolved:
                self.assertTrue(
                    resolved_file.startswith(str(tools)),
                    f"§S6/AC4: {resolved_file} was resolved from outside the "
                    f"relocated bundle {tools}.",
                )
            leaked = [
                entry for entry in path_entries
                if ".claude" in entry or entry == str(REPO_ROOT)
            ]
            self.assertEqual(
                [], leaked,
                f"§S6/AC4: the child's sys.path must carry no `~/.claude` "
                f"entry and no repo path; leaked {leaked}.",
            )
        finally:
            shutil.rmtree(sandbox, ignore_errors=True)



class AssetSlotGatesS7Test(unittest.TestCase):
    """§S7 — the asset slot stays full, complete, and honestly accounted."""

    def setUp(self):
        self.sandbox = Path(tempfile.mkdtemp(prefix="mdb022-c3-assets-"))

    def tearDown(self):
        shutil.rmtree(self.sandbox, ignore_errors=True)

    def _asset_root_copy(self) -> Path:
        copy = self.sandbox / "scripts"
        copy.mkdir()
        for path in _script_files(SCRIPTS_DIR):
            shutil.copy2(path, copy / path.name)
        return copy

    def test_s7_scripts_dir_holds_the_seven_adopted_plus_the_generated_codec(self):
        """STANDING GUARD (passes today): C1 filled the slot; this pins it."""
        violations = _asset_slot_violations(SCRIPTS_DIR)
        self.assertEqual(
            [], violations,
            f"§S7/AC1: scripts/ must hold exactly the seven ADOPTED names "
            f"{list(ADOPTED_SCRIPT_NAMES)} plus the one GENERATED "
            f"{list(GENERATED_SCRIPT_NAMES)}. Violations: {violations}",
        )
        for name in GENERATED_SCRIPT_NAMES:
            self.assertTrue(
                _carries_generated_banner(SCRIPTS_DIR / name),
                f"§S7/AC1: scripts/{name} is the GENERATED artifact (C2: "
                f"generator/build.py from modelb_axi/toon.py, gated by "
                f"--check) and must say so in its first {BANNER_WINDOW} lines "
                f"via {list(GENERATED_BANNER_MARKERS)} — otherwise it is "
                f"conflated with the adopted seven and a hand-edit passes "
                f"unnoticed.",
            )
        conflated = [
            name for name in ADOPTED_SCRIPT_NAMES
            if (SCRIPTS_DIR / name).is_file()
            and _carries_generated_banner(SCRIPTS_DIR / name)
        ]
        self.assertEqual(
            [], conflated,
            f"§S7/AC1: an ADOPTED script carries the generated-artifact "
            f"banner: {conflated}. Adopted scripts are hand-maintained here; "
            f"only {list(GENERATED_SCRIPT_NAMES)} is generated.",
        )

    def test_s7_gate_rejects_an_unlisted_addition_and_a_missing_name(self):
        """STANDING GUARD by MUTATION: a gate is only worth having if it
        discriminates, so break a throwaway copy and watch it fire."""
        root = self._asset_root_copy()
        self.assertEqual(
            [], _asset_slot_violations(root),
            "the unmutated copy of the asset root must be clean before any "
            "mutation is meaningful",
        )

        stray = root / "stray-tool.py"
        stray.write_text("# not part of the asset class\n", encoding="utf-8")
        addition_violations = _asset_slot_violations(root)
        self.assertTrue(
            any(stray.name in v for v in addition_violations),
            f"§S7/AC1: the gate must FAIL on an unlisted addition; adding "
            f"{stray.name} produced {addition_violations}.",
        )
        stray.unlink()
        self.assertEqual(
            [], _asset_slot_violations(root),
            "removing the stray addition must clear the violation",
        )

        victim = root / "worktree-flow.py"
        victim.unlink()
        removal_violations = _asset_slot_violations(root)
        self.assertTrue(
            any(victim.name in v for v in removal_violations),
            f"§S7/AC1: the gate must FAIL on a missing name; removing "
            f"{victim.name} produced {removal_violations}.",
        )

    def test_s7_gate_rejects_an_empty_asset_root(self):
        """STANDING GUARD by MUTATION: the empty asset root is the state every
        wheel shipped between CR-MDB-014 and this CR."""
        empty = self.sandbox / "empty-scripts"
        empty.mkdir()
        violations = _asset_slot_violations(empty)
        self.assertTrue(
            any("EMPTY" in v for v in violations),
            f"§S7/AC1: the gate must FAIL on an empty asset root — the "
            f"CR-MDB-014-to-CR-MDB-022 shipping state — but reported "
            f"{violations}.",
        )
        absent = self.sandbox / "no-such-scripts"
        self.assertNotEqual(
            [], _asset_slot_violations(absent),
            "§S7/AC1: the gate must FAIL when the asset root does not exist "
            "at all.",
        )

    def test_s7_every_script_is_consumed_or_carries_a_recorded_reason(self):
        present = {p.name for p in _script_files(SCRIPTS_DIR)}
        consumed = _consumed_names()

        self.assertNotIn(
            GATE_LOCK_SH.name, NO_CONSUMER_ALLOW_LIST,
            f"§S7/AC1: {GATE_LOCK_SH.name} must NOT be allow-listed — §S5 "
            f"gives it a consumer by naming it in "
            f"{_rel(ORCH_COMMON)}. Allow-listing it would excuse §S5 not "
            f"happening.",
        )
        stale = sorted(set(NO_CONSUMER_ALLOW_LIST) - present)
        self.assertEqual(
            [], stale,
            f"§S7/AC1: the allow-list names scripts that no longer exist: "
            f"{stale}. An allow-list entry is a live decision, not residue.",
        )

        unaccounted = sorted(
            name for name in present
            if name not in consumed and name not in NO_CONSUMER_ALLOW_LIST
        )
        self.assertEqual(
            [], unaccounted,
            f"§S7/AC1: every script under scripts/ must either have a "
            f"consuming-skill reference in-tree (directly under skills-src/, "
            f"or transitively through a sibling script that has one) or carry "
            f"an explicit, commented allow-list entry recording WHY it does "
            f"not yet. Unaccounted: {unaccounted}. A missing consumer is a "
            f"LEAD, not a licence to delete.",
        )

        for name, reason in NO_CONSUMER_ALLOW_LIST.items():
            self.assertNotIn(
                name, consumed,
                f"§S7/AC1: {name} now HAS a consuming reference, so its "
                f"allow-list entry is obsolete — remove it rather than let a "
                f"stale exemption hide a future orphan.",
            )
            for evidence_path, pattern in ALLOW_LIST_EVIDENCE.get(name, ()):
                if evidence_path is None:
                    self.assertRegex(
                        reason, pattern,
                        f"§S7/AC1: {name}'s allow-list reason must record its "
                        f"design lineage ({pattern.pattern}).",
                    )
                    continue
                self.assertTrue(
                    evidence_path.is_file(),
                    f"§S7/AC1: {name}'s recorded forward reference cites "
                    f"{_rel(evidence_path)}, which does not exist — the "
                    f"exemption rests on nothing.",
                )
                self.assertRegex(
                    _read(evidence_path), pattern,
                    f"§S7/AC1: {_rel(evidence_path)} no longer forward-"
                    f"references {name}; re-measure before keeping the "
                    f"exemption.",
                )

    def test_s7_built_wheel_carries_all_eight_tool_assets(self):
        """STANDING GUARD against CR-MDB-014's VERIFY defect class: assets
        absent from the wheel while dev-mode tests pass. Asserted against a
        genuinely BUILT artifact, never the source tree."""
        if importlib.util.find_spec("build") is None:
            self.skipTest(
                "the `build` frontend is unavailable, so no genuine wheel can "
                "be produced; the source tree is NOT an acceptable substitute "
                "for this AC (CR-MDB-014's VERIFY caught exactly that)"
            )
        outdir = self.sandbox / "dist"
        result = _run(
            [sys.executable, "-m", "build", "--wheel", "--no-isolation",
             "--outdir", str(outdir), str(REPO_ROOT)],
        )
        self.assertEqual(
            0, result.returncode,
            f"§S7/AC2: the wheel build failed: "
            f"{(result.stderr or result.stdout).strip()[-600:]}",
        )
        wheels = sorted(outdir.glob("*.whl"))
        self.assertEqual(
            1, len(wheels),
            f"§S7/AC2: expected exactly one built wheel, got "
            f"{[w.name for w in wheels]}",
        )
        with zipfile.ZipFile(wheels[0]) as archive:
            members = set(archive.namelist())
        missing = [
            name for name in TOOL_SCRIPT_NAMES
            if WHEEL_ASSET_PREFIX + name not in members
        ]
        self.assertEqual(
            [], missing,
            f"§S7/AC2: the built wheel {wheels[0].name} must carry all eight "
            f"tool scripts under {WHEEL_ASSET_PREFIX}; missing {missing}. "
            f"Present there: "
            f"{sorted(m for m in members if m.startswith(WHEEL_ASSET_PREFIX))}",
        )


if __name__ == "__main__":
    unittest.main()
