"""Agent definitions: neutral render + per-harness emitters (CR-MDB-025 §S1-§S3).

Each stack x role renders into a **neutral definition** — a plain dict with
``name``, ``description``, ``body``, ``tools`` (intent names), ``thinking``,
``skills`` (list) and, only when the stack TOML sets one, ``model`` — which a
per-harness emitter serialises. ``_emit_pi`` is the only emitter today (DN
§D17); a future harness is one more function in ``EMITTERS``.

Tool intents are translated to harness names through one module-level dict
(§S2); an unknown intent is dropped and the drop is recorded with a reason,
never passed through or renamed.

Stdlib only. Deterministic output: no timestamps, stable ordering.

Ownership (§S6): every rendered file carries a marker comment as its first
frontmatter line naming the generator and the sha256 of the rest of the file.
:func:`render_project` writes a project's definitions under that rule — it
writes missing files, rewrites intact-marker files, skips hand-modified ones
(unless forced) and never writes a same-named file without a marker.
"""

import hashlib
import tomllib
from pathlib import Path
from string import Template

from modelb_axi._fsutil import atomic_write

STACKS = ("arduino", "bun", "python", "quarkus", "rust")
ROLES = ("red", "green", "verify", "fix")

# §S2 — tool intent name -> Pi tool name. Lowercase Pi names only; an intent
# absent from this dict is dropped with a recorded reason.
PI_TOOL_NAMES = {
    "read": "read",
    "write": "write",
    "edit": "edit",
    "grep": "grep",
    "find": "find",
    "ls": "ls",
    "ctx_shell": "ctx_shell",
    "ctx_read": "ctx_read",
    "ctx_grep": "ctx_grep",
    "ctx_glob": "ctx_glob",
    "ctx_find": "ctx_find",
    "ctx_ls": "ctx_ls",
    "ctx_patch": "ctx_patch",
    "ctx_edit": "ctx_edit",
    "ctx_search": "ctx_search",
    "ctx_tree": "ctx_tree",
}

SKILLS_LINE_PREFIX = "Load these skills first:"

# §S4 — tool intents a role's permission policy denies outright, beside the
# allowlist. VERIFY is read-only, so the policy states it as well as the
# tools line (the allowlist never admits these for VERIFY — §S2).
ROLE_DENIED_TOOLS = {"verify": ("write", "edit")}

# §S6 — each harness's project agent directory, relative to the project
# root. Only harnesses with an emitter (EMITTERS) have one.
PROJECT_AGENT_DIRS = {"pi": Path(".pi") / "agents"}

# §S6 Ownership — the marker comment's fixed prefix; the sha256 hex digest of
# the file without this line follows it.
MARKER_PREFIX = "# generated by modelb-axi (Model B agents); sha256 "

# §S6 — the ownership states :func:`ownership_state` reports.
OWNED_INTACT = "intact"
OWNED_HAND_MODIFIED = "hand_modified"
NOT_OWNED = "unmanaged"


def load_stack_params(stacks_dir: Path, stack: str) -> dict:
    """Parse one stack TOML (``<stacks_dir>/<stack>.toml``) via tomllib."""
    with (stacks_dir / f"{stack}.toml").open("rb") as fh:
        return tomllib.load(fh)


def neutral_definition(stack: str, role: str, params: dict, templates_dir: Path) -> dict:
    """Render one stack x role into the harness-neutral definition dict."""
    role_table = params["roles"][role]
    template = Template((templates_dir / f"{role}.md.tmpl").read_text(encoding="utf-8"))
    body = template.substitute({
        "display_name": params["display_name"],
        "test_command": params["test_command"],
        "register_command": params["register_command"],
        "unregister_command": params["unregister_command"],
        "crucible_reference": params["crucible_reference"],
        "stack_mechanics": params["mechanics"].strip("\n"),
        "role_gotchas": params["gotchas"][role].strip("\n"),
        # CR-MDB-017 §S6b: the per-stack half of the tier-guidance section.
        "tier_guidance": params["tier_guidance"].strip(),
    })
    defn = {
        "name": f"{stack}-{role}-agent",
        "description": params["description"][role],
        "body": body.strip("\n") + "\n",
        "tools": list(role_table["tools"]),
        "thinking": role_table["thinking"],
        "skills": list(role_table.get("skills", [])),
        "deny": list(ROLE_DENIED_TOOLS.get(role, ())),
    }
    if role_table.get("model"):
        defn["model"] = role_table["model"]
    return defn


def translate_tools(intents: list[str], table: dict[str, str]) -> tuple[list[str], list[dict]]:
    """Translate intent names through ``table``; return (names, drops).

    Order-preserving and de-duplicated. Each drop is a dict naming the
    ``intent`` and the ``reason`` it was dropped.
    """
    names: list[str] = []
    drops: list[dict] = []
    for intent in intents:
        name = table.get(intent)
        if name is None:
            drops.append({"intent": intent, "reason": "unknown tool intent: no harness translation"})
            continue
        if name not in names:
            names.append(name)
    return names, drops


def _emit_pi(defn: dict, drops: list[dict] | None = None) -> str:
    """Serialise a neutral definition as a Pi (``@gotgenes/pi-subagents``) file.

    Frontmatter carries only what the reader reads (§S3): ``name``,
    ``description``, ``tools`` (one comma-separated string), ``thinking``,
    ``permission`` (§S4: ``allow`` for exactly the emitted tools, then
    ``deny`` for the definition's optional ``deny`` intents), and ``model``
    only when the definition sets one. Skills become one body line.
    Dropped tool intents are appended to ``drops`` (when given), each tagged
    with the definition name.
    """
    tools, dropped = translate_tools(defn["tools"], PI_TOOL_NAMES)
    denied, dropped_denies = translate_tools(defn.get("deny", []), PI_TOOL_NAMES)
    if drops is not None:
        drops.extend({"name": defn["name"], **d} for d in dropped + dropped_denies)
    lines = [
        "---",
        f"name: {defn['name']}",
        f"description: {defn['description']}",
        f"tools: {', '.join(tools)}",
        f"thinking: {defn['thinking']}",
        "permission:",
        *(f"  {tool}: allow" for tool in tools),
        *(f"  {tool}: deny" for tool in denied if tool not in tools),
    ]
    if defn.get("model"):
        lines.append(f"model: {defn['model']}")
    lines.extend(["---", ""])
    if defn["skills"]:
        lines.extend([f"{SKILLS_LINE_PREFIX} {', '.join(defn['skills'])}.", ""])
    return "\n".join(lines) + "\n" + defn["body"]


EMITTERS = {"pi": _emit_pi}


def render(
    stack: str,
    role: str,
    params: dict,
    templates_dir: Path,
    harness: str = "pi",
    drops: list[dict] | None = None,
) -> str:
    """Render one stack x role for ``harness``: neutral definition, emit, then
    stamp the §S6 ownership marker."""
    emitted = EMITTERS[harness](neutral_definition(stack, role, params, templates_dir), drops)
    return _with_marker(emitted)

def _sha256_text(text: str) -> str:
    return hashlib.sha256(text.encode("utf-8")).hexdigest()

def _with_marker(content: str) -> str:
    """Insert the ownership marker as the first frontmatter line (right after
    the opening ``---``); its digest is the sha256 of ``content`` itself, so
    removing the marker line restores exactly what was hashed."""
    head, _, rest = content.partition("\n")
    return f"{head}\n{MARKER_PREFIX}{_sha256_text(content)}\n{rest}"

def ownership_state(text: str) -> str:
    """Classify an existing file (§S6 Ownership).

    ``intact`` — the frontmatter carries the marker and its digest matches the
    rest of the file; ``hand_modified`` — the marker is present but the digest
    does not match; ``unmanaged`` — no marker inside a frontmatter block.
    """
    lines = text.splitlines(keepends=True)
    if not lines or lines[0].rstrip("\r\n") != "---":
        return NOT_OWNED
    for idx in range(1, len(lines)):
        stripped = lines[idx].rstrip("\r\n")
        if stripped == "---":
            break
        if stripped.startswith(MARKER_PREFIX):
            recorded = stripped[len(MARKER_PREFIX):].strip()
            rest = "".join(lines[:idx] + lines[idx + 1:])
            return OWNED_INTACT if _sha256_text(rest) == recorded else OWNED_HAND_MODIFIED
    return NOT_OWNED

def render_project(
    project_root: Path,
    stacks: list[str],
    harnesses: list[str],
    templates_dir: Path,
    stacks_dir: Path,
    *,
    force_managed: bool = False,
    report: dict | None = None,
) -> dict:
    """Render the project's definitions into each harness's project agent
    directory under the §S6 ownership rules.

    Harnesses without an emitter and stacks without a stack TOML under
    ``stacks_dir`` render nothing (the latter are listed under
    ``no_definitions``). Only the ``<stack>-<role>-agent.md`` names this
    render owns are ever read or written — no other file in the directory is
    touched, and nothing is deleted.

    Returns (and fills, per file as it goes, when given) ``report`` with
    lists of project-relative paths: ``written``, ``unchanged``, ``skipped``
    (hand-modified, left as-is) and ``unmanaged`` (no marker, never written),
    plus ``no_definitions`` (stack ids).
    """
    if report is None:
        report = {}
    for key in ("written", "unchanged", "skipped", "unmanaged", "no_definitions"):
        report.setdefault(key, [])
    renderable = []
    for stack in stacks:
        if (stacks_dir / f"{stack}.toml").is_file():
            renderable.append(stack)
        elif stack not in report["no_definitions"]:
            report["no_definitions"].append(stack)
    for harness in harnesses:
        reldir = PROJECT_AGENT_DIRS.get(harness)
        if reldir is None or harness not in EMITTERS:
            continue
        for stack in renderable:
            params = load_stack_params(stacks_dir, stack)
            for role in ROLES:
                rel = reldir / f"{stack}-{role}-agent.md"
                content = render(stack, role, params, templates_dir, harness=harness)
                _place(project_root / rel, str(rel), content, force_managed, report)
    return report

def _place(path: Path, rel: str, content: str, force_managed: bool, report: dict) -> None:
    """Apply the §S6 ownership rules to one target file."""
    if path.exists():
        existing = path.read_bytes().decode("utf-8", errors="replace")
        state = ownership_state(existing)
        if state == NOT_OWNED:
            report["unmanaged"].append(rel)
            return
        if state == OWNED_HAND_MODIFIED and not force_managed:
            report["skipped"].append(rel)
            return
        if existing == content:
            report["unchanged"].append(rel)
            return
    path.parent.mkdir(parents=True, exist_ok=True)
    atomic_write(path, content.encode("utf-8"))
    report["written"].append(rel)
