"""The workflow permission policy for Pi's ``@gotgenes/pi-permission-system``
(CR-MDB-037 §S3).

- :func:`render_policy` renders the per-project policy
  (``<target>/.pi/extensions/pi-permission-system/config.json``): JSON whose
  FIRST line is CR-MDB-025 §S6's ownership marker as a ``//`` comment (the
  package's loader strips comments; a marker KEY would make the file invalid
  and clamp the project to ``ask``). ``"*": "ask"`` is the explicit fallback;
  ``allow`` goes by exact tool name to :func:`workflow_tools` — the
  ``dispatch`` and ``lean-ctx`` names read from
  :data:`modelb_axi.requirements.REQUIREMENTS` at call time, never restated.
- :func:`place_project_policy` writes it under the §S6 ownership rules
  (:func:`modelb_axi.agents.place_owned`).

The installer no longer reads or reports the user's GLOBAL config
(CR-MDB-038 §S3); Model B never writes it.

Stdlib only.
"""

import hashlib
import json
import shutil
from pathlib import Path

from modelb_axi import agents, requirements

#: The policy file, relative to a project's ``.pi`` directory.
POLICY_RELPATH = Path("extensions") / "pi-permission-system" / "config.json"
PROJECT_POLICY_RELPATH = Path(".pi") / POLICY_RELPATH

#: The ownership marker line, minus its sha256 hex (§S3 / CR-MDB-025 §S6).
MARKER_PREFIX = "// generated by modelb-axi (Model B permission policy); sha256 "

#: The built-in file tools (ruling P5 — no ``bash``).
BUILTIN_FILE_TOOLS: tuple[str, ...] = ("read", "write", "edit", "grep", "find", "ls")
#: The UI tools and the child-side tools.
FIXED_WORKFLOW_TOOLS: tuple[str, ...] = (
    "todo", "ask_user_question", "notify_parent", "ask_parent",
)
#: The requirement rows whose ``tools`` the policy allows.
_TOOL_REQUIREMENTS: tuple[str, ...] = ("dispatch", "lean-ctx")

#: External-directory reads allowed for every project (the installed
#: harness's own code is added by :func:`_harness_code_reads`).
_EXTERNAL_READS: tuple[str, ...] = ("~/.agents/*", "~/.crucible/*", "~/.pi/agent/*")
_TMP = "/tmp/*"  # noqa: S108 -- the spec's pattern, not a temp file



def workflow_tools() -> list[str]:
    """The §S3 allow-set, sorted, derived from ``REQUIREMENTS`` now."""
    tools: set[str] = set(BUILTIN_FILE_TOOLS) | set(FIXED_WORKFLOW_TOOLS)
    for requirement_id in _TOOL_REQUIREMENTS:
        tools |= set(requirements.requirement(requirement_id)["tools"])
    return sorted(tools)


def _harness_code_reads() -> list[str]:
    """``~/.bun/install/*`` when the ``pi`` on PATH is a bun-installed Pi
    (§S3: the installed harness's own code); else nothing."""
    found = shutil.which("pi")
    if found is None:
        return []
    bun_install = Path.home() / ".bun" / "install"
    if Path(found).resolve().is_relative_to(bun_install.resolve()):
        return ["~/.bun/install/*"]
    return []


def _sha256_text(text: str) -> str:
    return hashlib.sha256(text.encode("utf-8")).hexdigest()


def render_policy() -> str:
    """The project policy text: marker line, then the JSON body. Maps put
    ``"*"`` first — the package's last matching pattern wins."""
    permission: dict = {"*": "ask"}
    permission.update(dict.fromkeys(workflow_tools(), "allow"))
    permission["skill"] = "allow"
    reads = {"*": "ask"}
    reads.update(dict.fromkeys((*_EXTERNAL_READS, *_harness_code_reads(), _TMP), "allow"))
    permission["external_directory_read"] = reads
    permission["external_directory_write"] = {"*": "ask", _TMP: "allow"}
    body = json.dumps({"permission": permission}, indent=2) + "\n"
    return f"{MARKER_PREFIX}{_sha256_text(body)}\n{body}"


def ownership_state(text: str) -> str:
    """Classify an existing policy file: ``intact`` when its first line is
    the marker and the digest matches the rest; ``hand_modified`` when the
    marker is there but the digest does not match; ``unmanaged`` otherwise."""
    first, _, rest = text.partition("\n")
    first = first.rstrip("\r")
    if not first.startswith(MARKER_PREFIX):
        return agents.NOT_OWNED
    recorded = first[len(MARKER_PREFIX):].strip()
    if recorded == _sha256_text(rest):
        return agents.OWNED_INTACT
    return agents.OWNED_HAND_MODIFIED


def place_project_policy(
    project_root: Path, *, force_managed: bool = False, report: dict | None = None,
) -> dict:
    """Write the project policy under the §S6 ownership rules; returns (and
    fills, when given) ``report`` with ``written`` / ``unchanged`` /
    ``skipped`` / ``unmanaged`` project-relative paths."""
    if report is None:
        report = {}
    for key in ("written", "unchanged", "skipped", "unmanaged"):
        report.setdefault(key, [])
    rel = str(PROJECT_POLICY_RELPATH)
    agents.place_owned(
        project_root / rel, rel, render_policy(), force_managed, report,
        classify=ownership_state,
    )
    return report
